files: ^app/|^alembic/versions/
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        name: Ruff linter
        args: [ "--fix" ]
      - id: ruff-format
        name: Ruff formatter

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
      - id: mypy
        exclude: ^alembic/
        additional_dependencies: [
          pydantic==2.5.1,
          SQLAlchemy==2.0.25,
        ]
