"""DB Init

Revision ID: 67962fd385e8
Revises:
Create Date: 2023-11-17 22:47:50.989999+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "67962fd385e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "examples",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("text", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_examples")),
    )
    op.create_index(op.f("ix_examples_text"), "examples", ["text"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_examples_text"), table_name="examples")
    op.drop_table("examples")
    # ### end Alembic commands ###
